---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alarmprovider
data:
  PORT: "8080"
  DB_HOST: "couchdb:5984"
  DB_PROTOCOL: "http"
  DB_PREFIX: "whisk_alarms_"
  ROUTER_HOST: "nginx"
  CONTROLLER_HOST: "controller-0.controller"
  CONTROLLER_HOST_PORT: "8080"
  AUTH_WHISK_SYSTEM: "789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alarmprovider
  labels:
    name: alarmprovider
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: alarmprovider
    spec:
      restartPolicy: Always
      containers:
      - name: alarmprovider
        imagePullPolicy: IfNotPresent
        image: openwhisk/alarmprovider:1.1.7
        command: [ "/bin/bash", "-c", "node /alarmsTrigger/app.js" ]
        envFrom:
        - configMapRef:
            name: alarmprovider
        env:
        - name: "DB_USERNAME"
          valueFrom:
            secretKeyRef:
              name: "couchdb"
              key: "username"
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "couchdb"
              key: "password"
      initContainers:
      - name: install-alarms-catalog
        imagePullPolicy: IfNotPresent
        image: projectodd/whisk_alarms:openshift-latest
        envFrom:
        - configMapRef:
            name: alarmprovider
