---
apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    name: controller
spec:
  selector:
    name: controller
  clusterIP: None
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: controller
data:
  init: |
    source /openwhisk_config/env
    exec /controller/bin/controller $(hostname | cut -d'-' -f2)
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: controller
  labels:
    name: controller
spec:
  replicas: 2
  serviceName: "controller"
  template:
    metadata:
      labels:
        name: controller
    spec:
      restartPolicy: Always
      volumes:
      - name: openwhisk-config
        configMap:
          name: openwhisk-config
      - name: controller-config
        configMap:
          name: controller
      containers:
      - name: controller
        imagePullPolicy: IfNotPresent
        image: projectodd/controller:openshift-latest
        command: ["/bin/bash", "-o", "allexport", "/controller_config/init" ]
        ports:
        - name: controller
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: "/ping"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: "/ping"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        env:
        # Database credentials
        - name: "DB_USERNAME"
          valueFrom:
            secretKeyRef:
              name: "couchdb"
              key: "username"
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "couchdb"
              key: "password"
        volumeMounts:
        - name: openwhisk-config
          mountPath: "/openwhisk_config"
        - name: controller-config
          mountPath: "/controller_config"
      initContainers:
      - name: wait-for-couchdb
        image: busybox
        command: ['sh', '-c', 'until wget -T 5 --spider http://couchdb:5984/_all_dbs; do echo waiting for couchdb; sleep 2; done;']
---
apiVersion: batch/v1
kind: Job
metadata:
  name: install-openwhisk-catalog
  labels:
    name: install-openwhisk-catalog
spec:
  completions: 1
  template:
    metadata:
      labels:
        name: install-openwhisk-catalog
    spec:
      restartPolicy: Never
      volumes:
      - name: openwhisk-config
        configMap:
          name: openwhisk-config
      containers:
      - name: install-openwhisk-catalog
        image: projectodd/whisk_catalog:openshift-latest
        imagePullPolicy: IfNotPresent
        env:
        - name: "AUTH_WHISK_SYSTEM"
          valueFrom:
            secretKeyRef:
              name: "openwhisk"
              key: "system"
        volumeMounts:
        - name: openwhisk-config
          mountPath: "/openwhisk_config"
