---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
  labels:
    name: couchdb
spec:
  selector:
    name: couchdb
  ports:
    - port: 5984
      targetPort: 5984
      name: couchdb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: couchdb
  labels:
    name: couchdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: couchdb
    spec:
      restartPolicy: Always
      volumes:
      - name: openwhisk-config
        configMap:
          name: openwhisk-config
      - name: couchdb-data
        emptyDir: {}
      containers:
      - name: couchdb
        imagePullPolicy: IfNotPresent
        image: projectodd/whisk_couchdb:openshift-latest
        ports:
        - name: couchdb
          containerPort: 5984
        env:
        - name: "DB_USERNAME"
          valueFrom:
            secretKeyRef:
              name: "couchdb"
              key: "username"
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "couchdb"
              key: "password"
        volumeMounts:
          - name: openwhisk-config
            mountPath: "/openwhisk_config"
          - name: couchdb-data
            mountPath: "/usr/local/var/lib/couchdb"
