---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
  labels:
    name: couchdb
spec:
  selector:
    name: couchdb
  ports:
    - port: 5984
      targetPort: 5984
      name: couchdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb
data:
  init: |
    source /openwhisk_config/env
    exec /init.sh
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: couchdb
  labels:
    name: couchdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: couchdb
    spec:
      restartPolicy: Always
      volumes:
      - name: openwhisk-config
        configMap:
          name: openwhisk-config
      - name: couchdb-config
        configMap:
          name: couchdb
      - name: couchdb-data
        emptyDir: {}
      containers:
      - name: couchdb
        imagePullPolicy: IfNotPresent
        image: projectodd/whisk_couchdb:openshift-latest
        command: ["/bin/bash", "-o", "allexport", "/couchdb_config/init" ]
        ports:
        - name: couchdb
          containerPort: 5984
        env:
        - name: "NODENAME"
          value: "couchdb0"
        # Database credentials
        - name: "COUCHDB_USER"
          valueFrom:
            secretKeyRef:
              name: "couchdb"
              key: "username"
        - name: "COUCHDB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "couchdb"
              key: "password"
        # Authentication tokens
        - name: "AUTH_WHISK_SYSTEM"
          valueFrom:
            secretKeyRef:
              name: "openwhisk"
              key: "system"
        - name: "AUTH_GUEST"
          valueFrom:
            secretKeyRef:
              name: "openwhisk"
              key: "guest"
        volumeMounts:
          - name: openwhisk-config
            mountPath: "/openwhisk_config"
          - name: couchdb-config
            mountPath: "/couchdb_config"
          - name: couchdb-data
            mountPath: "/usr/local/var/lib/couchdb"
