---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    name: kafka
spec:
  selector:
    name: kafka
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka
  labels:
    name: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka
    spec:
      restartPolicy: Always
      volumes:
      - name: kafka-logs
        emptyDir: {}
      - name: kafka-java-logs
        emptyDir: {}
      containers:
      - name: kafka
        imagePullPolicy: IfNotPresent
        image: projectodd/whisk_kafka:openshift-latest
        ports:
        - name: kafka
          containerPort: 9092
        env:
        - name: "KAFKA_ADVERTISED_HOST_NAME"
          value: kafka
        - name: "KAFKA_PORT"
          value: "9092"

        # message settings
        - name: "REPLICATION_FACTOR"
          value: "1"
        - name: "PARTITIONS"
          value: "1"

        # health topic settings
        - name: "KAFKA_TOPICS_HEALTH_RETENTIONBYTES"
          value: "536870912"
        - name: "KAFKA_TOPICS_HEALTH_RETENTIONMS"
          value: "1073741824"
        - name: "KAFKA_TOPICS_HEALTH_SEGMENTBYTES"
          value: "3600000"

        # complete topic settings
        - name: "CONTROLLER_COUNT"
          value: "2"
        - name: "KAFKA_TOPICS_COMPLETED_RETENTIONBYTES"
          value: "536870912"
        - name: "KAFKA_TOPICS_COMPLETED_RETENTIONMS"
          value: "1073741824"
        - name: "KAFKA_TOPICS_COMPLETED_SEGMENTBYTES"
          value: "3600000"

        # invoker topic settings
        - name: "INVOKER_COUNT"
          value: "1"
        - name: "KAFKA_TOPICS_INVOKER_RETENTIONBYTES"
          value: "536870912"
        - name: "KAFKA_TOPICS_INVOKER_RETENTIONMS"
          value: "1073741824"
        - name: "KAFKA_TOPICS_INVOKER_SEGMENTBYTES"
          value: "3600000"

        # zookeeper info
        - name: "ZOOKEEPER_HOST"
          value: "zookeeper"
        - name: "ZOOKEEPER_PORT"
          value: "2181"
        volumeMounts:
          - name: kafka-logs
            mountPath: "/data"
          - name: kafka-java-logs
            mountPath: "/logs"
