---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  selector:
    name: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
      name: zookeeper
    - port: 2888
      targetPort: 2888
      name: server
    - port: 3888
      targetPort: 3888
      name: leader-election
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      restartPolicy: Always
      volumes:
      - name: zookeeper-data
        emptyDir: {}
      - name: zookeeper-datalog
        emptyDir: {}
      containers:
      - name: zookeeper
        image: projectodd/whisk_zookeeper:openshift-latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: zookeeper
          containerPort: 2181
        - name: server
          containerPort: 2888
        - name: leader-election
          containerPort: 3888
        volumeMounts:
          - mountPath: /data
            name: zookeeper-data
          - mountPath: /datalog
            name: zookeeper-datalog
