---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: invoker
  namespace: openwhisk
  labels:
    name: invoker
spec:
  replicas: 1
  serviceName: "invoker"
  template:
    metadata:
      labels:
        name: invoker
    spec:
      restartPolicy: Always
      serviceAccountName: openwhisk
      containers:
      - name: invoker
        # imagePullPolicy: Always
        image: whisk/invoker:123
        command: [ "/bin/bash", "-c", "COMPONENT_NAME=$(hostname | cut -d'-' -f2) /invoker/bin/invoker `hostname | cut -d'-' -f2`" ]
        env:
          - name: "CONSULSERVER_HOST"
            value: "consul.openwhisk"
          - name: "CONSUL_HOST_PORT4"
            value: "8500"
          - name: "PORT"
            value: "8080"
          - name: "SERVICE_CHECK_HTTP"
            value: "/ping"
          - name: "SERVICE_CHECK_TIMEOUT"
            value: "2s"
          - name: "SERVICE_CHECK_INTERVAL"
            value: "15s"
          - name: "INVOKER_USEREACTIVEPOOL"
            value: "true"
          - name: "INVOKER_USEKUBERNETES"
            value: "true"
        ports:
        - name: invoker
          containerPort: 8080
