---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openwhisk
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: openwhisk
roleRef:
  name: edit
subjects:
  - kind: ServiceAccount
    name: openwhisk
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openwhisk-config
data:
  env: |
    WHISK_API_HOST_NAME=nginx
    WHISK_VERSION_NAME=kube
    WHISK_LOGS_DIR=/tmp/wsklogs
    WHISK_VERSION_DATE=2017-05-25T01:36:40Z
    WHISK_VERSION_BUILDNO=latest
  
    RUNTIMES_MANIFEST='{"defaultImagePrefix": "openwhisk", "defaultImageTag": "latest", "blackboxes": [{"name": "dockerskeleton"}], "runtimes": {"python": [{"kind": "python", "image": {"name": "python2action"}}, {"default": true, "kind": "python:2", "image": {"name": "python2action"}}, {"kind": "python:3", "image": {"name": "python3action"}}], "swift": [{"deprecated": true, "kind": "swift", "image": {"name": "swiftaction"}}, {"default": true, "kind": "swift:3", "image": {"name": "swift3action"}}], "java": [{"kind": "java", "default": true, "image": {"name": "java8action"}, "attached": {"attachmentType": "application/java-archive", "attachmentName": "jarfile"}, "sentinelledLogs": false, "requireMain": true}], "nodejs": [{"deprecated": true, "kind": "nodejs", "image": {"name": "nodejsaction"}}, {"default": true, "kind": "nodejs:6", "image": {"name": "nodejs6action"}}]}}'
    
    DEFAULTLIMITS_ACTIONS_INVOKES_PERMINUTE=120
    DEFAULTLIMITS_ACTIONS_INVOKES_CONCURRENT=100
    DEFAULTLIMITS_ACTIONS_INVOKES_CONCURRENTINSYSTEM=5000
    DEFAULTLIMITS_ACTIONS_SEQUENCE_MAXLENGTH=50
    DEFAULTLIMITS_TRIGGERS_FIRES_PERMINUTE=60

    LIMITS_ACTIONS_INVOKES_PERMINUTE=60
    LIMITS_ACTIONS_INVOKES_CONCURRENT=30
    LIMITS_ACTIONS_INVOKES_CONCURRENTINSYSTEM=5000
    LIMITS_TRIGGERS_FIRES_PERMINUTE=60

    CONTROLLER_HOST=controller-0.controller
    CONTROLLER_HOST_PORT=8080

    CONSULSERVER_HOST=consul
    CONSUL_HOST=consul
    CONSUL_HOST_PORT4=8500
    
    KAFKA_HOST=kafka
    KAFKA_HOST_PORT=9092
    KAFKA_NUMPARTITIONS=2

    ZOOKEEPER_HOST=zookeeper
    ZOOKEEPER_HOST_PORT=2181

    INVOKER_CONTAINER_NETWORK=bridge
    INVOKER_USEREACTIVEPOOL=true
    INVOKER_NUMCORE=4
    INVOKER_CORESHARE=3
    
    NGINX_HOST=nginx
    NGINX_CONF_DIR=/tmp/nginx

    DB_HOST=couchdb
    DB_PROVIDER=CouchDB
    DB_PORT=5984
    DB_PROTOCOL=http
    DB_AUTH="subjects"
    DB_PREFIX="openwhisk_kube_"
    DB_SPLIT_ACTIONS_AND_ACTIVATIONS=true
    DB_WHISK_ACTIONS=openwhisk_kube_whisks
    DB_WHISK_ACTIVATIONS=openwhisk_kube_activations
    DB_WHISK_AUTHS=openwhisk_kube_subjects

    APIGW_AUTH_USER=""
    APIGW_AUTH_PWD=""
    APIGW_HOST="nginx"
    APIGW_HOST_V2="nginx"

    DOCKER_DNS=""
    DOCKER_REGISTRY=""
    DOCKER_IMAGE_PREFIX="projectodd"
    DOCKER_IMAGE_TAG="openshift-latest"

    LOADBALANCER_ACTIVATIONCOUNTBEFORENEXTINVOKER=10

    AUTH_WHISK_SYSTEM=789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
    AUTH_GUEST=23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP

    CATALOG_NAMESPACE="/whisk.system"
    CATALOG_AUTH_KEY="/openwhisk/ansible/files/auth.whisk.system"
---
apiVersion: v1
kind: Secret
metadata:
  name: couchdb
type: Opaque
data:
  password: Y291Y2hfcGFzc3dvcmQ=
  username: Y291Y2hfdXNlcm5hbWU=
