---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openwhisk
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: openwhisk
roleRef:
  name: edit
subjects:
  - kind: ServiceAccount
    name: openwhisk
