---
apiVersion: v1
kind: RoleBinding
metadata:
  name: openwhisk
roleRef:
  name: edit
subjects:
  - kind: ServiceAccount
    name: openwhisk
---
apiVersion: batch/v1
kind: Job
metadata:
  name: configure-openwhisk
  namespace: openwhisk
  labels:
    name: configure-openwhisk
spec:
  completions: 1
  template:
    metadata:
      labels:
        name: config
    spec:
      restartPolicy: Never
      serviceAccountName: openwhisk
      containers:
      - name: configure-openwhisk
        image: projectodd/whisk_config:v1.5.6-dev
        # imagePullPolicy: Always
        command: [ "/incubator-openwhisk-deploy-kube/configure/configure.sh" ]
