---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openwhisk
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: openwhisk
roleRef:
  name: edit
subjects:
  - kind: ServiceAccount
    name: openwhisk
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openwhisk-config
data:
  env: |
    WHISK_API_HOST_NAME=nginx
    WHISK_VERSION_NAME=kube
    WHISK_LOGS_DIR=/tmp/wsklogs
    WHISK_VERSION_DATE=2017-05-25T01:36:40Z
    WHISK_VERSION_BUILDNO=latest
  
    RUNTIMES_MANIFEST='{"defaultImagePrefix": "openwhisk", "defaultImageTag": "latest", "blackboxes": [{"name": "dockerskeleton"}], "runtimes": {"python": [{"kind": "python", "image": {"name": "python2action"}}, {"default": true, "kind": "python:2", "image": {"name": "python2action"}}, {"kind": "python:3", "image": {"name": "python3action"}}], "swift": [{"deprecated": true, "kind": "swift", "image": {"name": "swiftaction"}}, {"default": true, "kind": "swift:3", "image": {"name": "swift3action"}}], "java": [{"kind": "java", "default": true, "image": {"name": "java8action"}, "attached": {"attachmentType": "application/java-archive", "attachmentName": "jarfile"}, "sentinelledLogs": false, "requireMain": true}], "nodejs": [{"deprecated": true, "kind": "nodejs", "image": {"name": "nodejsaction"}}, {"default": true, "kind": "nodejs:6", "image": {"name": "nodejs6action"}}]}}'
    
    DEFAULTLIMITS_ACTIONS_INVOKES_PERMINUTE=120
    DEFAULTLIMITS_ACTIONS_INVOKES_CONCURRENT=100
    DEFAULTLIMITS_ACTIONS_INVOKES_CONCURRENTINSYSTEM=5000
    DEFAULTLIMITS_ACTIONS_SEQUENCE_MAXLENGTH=50
    DEFAULTLIMITS_TRIGGERS_FIRES_PERMINUTE=60

    LIMITS_ACTIONS_INVOKES_PERMINUTE=60
    LIMITS_ACTIONS_INVOKES_CONCURRENT=30
    LIMITS_ACTIONS_INVOKES_CONCURRENTINSYSTEM=5000
    LIMITS_TRIGGERS_FIRES_PERMINUTE=60

    CONTROLLER_HOST=controller-0.controller
    CONTROLLER_HOST_PORT=8080

    CONSULSERVER_HOST=consul
    CONSUL_HOST=consul
    CONSUL_HOST_PORT4=8500
    
    KAFKA_HOST=kafka
    KAFKA_HOST_PORT=9092
    KAFKA_NUMPARTITIONS=2

    ZOOKEEPER_HOST=zookeeper
    ZOOKEEPER_HOST_PORT=2181

    INVOKER_CONTAINER_NETWORK=bridge
    INVOKER_USEREACTIVEPOOL=true
    INVOKER_USEKUBERNETES=true
    INVOKER_NUMCORE=4
    INVOKER_CORESHARE=3
    
    NGINX_HOST=nginx
    NGINX_CONF_DIR=/tmp/nginx

    DB_HOST=couchdb
    DB_PROVIDER=CouchDB
    DB_PORT=5984
    DB_PROTOCOL=http
    DB_USERNAME=couch_user
    DB_PASSWORD=couch_password
    DB_AUTH="subjects"
    DB_PREFIX="openwhisk_kube_"
    DB_SPLIT_ACTIONS_AND_ACTIVATIONS=true
    DB_WHISK_ACTIONS=openwhisk_kube_whisks
    DB_WHISK_ACTIVATIONS=openwhisk_kube_activations
    DB_WHISK_AUTHS=openwhisk_kube_subjects

    APIGW_AUTH_USER=""
    APIGW_AUTH_PWD=""
    APIGW_HOST="nginx"
    APIGW_HOST_V2="nginx"

    DOCKER_DNS=""
    DOCKER_REGISTRY=""
    DOCKER_IMAGE_PREFIX="projectodd"
    DOCKER_IMAGE_TAG="openshift-latest"

    LOADBALANCER_ACTIVATIONCOUNTBEFORENEXTINVOKER=10

    AUTH_WHISK_SYSTEM=789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
    AUTH_GUEST=23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP

    CATALOG_NAMESPACE="/whisk.system"
    CATALOG_AUTH_KEY="/openwhisk/ansible/files/auth.whisk.system"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: couchdb
  labels:
    name: couchdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: couchdb
    spec:
      restartPolicy: Always
      volumes:
      - name: openwhisk-config
        configMap:
          name: openwhisk-config
      - name: couchdb-data
        emptyDir: {}
      containers:
      - name: couchdb
        imagePullPolicy: IfNotPresent
        image: projectodd/whisk_couchdb:openshift-latest
        ports:
        - name: couchdb
          containerPort: 5984
        volumeMounts:
          - name: openwhisk-config
            mountPath: "/openwhisk_config"
          - name: couchdb-data
            mountPath: "/usr/local/var/lib/couchdb"
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
  labels:
    name: couchdb
spec:
  selector:
    name: couchdb
  ports:
    - port: 5984
      targetPort: 5984
      name: couchdb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      restartPolicy: Always
      volumes:
      - name: zookeeper-data
        emptyDir: {}
      - name: zookeeper-datalog
        emptyDir: {}
      containers:
      - name: zookeeper
        image: projectodd/whisk_zookeeper:openshift-latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: zookeeper
          containerPort: 2181
        - name: server
          containerPort: 2888
        - name: leader-election
          containerPort: 3888
        volumeMounts:
          - mountPath: /data
            name: zookeeper-data
          - mountPath: /datalog
            name: zookeeper-datalog
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  selector:
    name: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
      name: zookeeper
    - port: 2888
      targetPort: 2888
      name: server
    - port: 3888
      targetPort: 3888
      name: leader-election
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka
  labels:
    name: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka
    spec:
      restartPolicy: Always
      volumes:
      - name: kafka-logs
        emptyDir: {}
      - name: kafka-java-logs
        emptyDir: {}
      containers:
      - name: kafka
        imagePullPolicy: IfNotPresent
        image: projectodd/whisk_kafka:openshift-latest
        ports:
        - name: kafka
          containerPort: 9092
        env:
        - name: "KAFKA_ADVERTISED_HOST_NAME"
          value: kafka
        - name: "KAFKA_PORT"
          value: "9092"

        # message settings
        - name: "REPLICATION_FACTOR"
          value: "1"
        - name: "PARTITIONS"
          value: "1"

        # health topic settings
        - name: "KAFKA_TOPICS_HEALTH_RETENTIONBYTES"
          value: "536870912"
        - name: "KAFKA_TOPICS_HEALTH_RETENTIONMS"
          value: "1073741824"
        - name: "KAFKA_TOPICS_HEALTH_SEGMENTBYTES"
          value: "3600000"

        # complete topic settings
        - name: "CONTROLLER_COUNT"
          value: "2"
        - name: "KAFKA_TOPICS_COMPLETED_RETENTIONBYTES"
          value: "536870912"
        - name: "KAFKA_TOPICS_COMPLETED_RETENTIONMS"
          value: "1073741824"
        - name: "KAFKA_TOPICS_COMPLETED_SEGMENTBYTES"
          value: "3600000"

        # invoker topic settings
        - name: "INVOKER_COUNT"
          value: "1"
        - name: "KAFKA_TOPICS_INVOKER_RETENTIONBYTES"
          value: "536870912"
        - name: "KAFKA_TOPICS_INVOKER_RETENTIONMS"
          value: "1073741824"
        - name: "KAFKA_TOPICS_INVOKER_SEGMENTBYTES"
          value: "3600000"

        # zookeeper info
        - name: "ZOOKEEPER_HOST"
          value: "zookeeper"
        - name: "ZOOKEEPER_PORT"
          value: "2181"
        volumeMounts:
          - name: kafka-logs
            mountPath: "/data"
          - name: kafka-java-logs
            mountPath: "/logs"
            
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    name: kafka
spec:
  selector:
    name: kafka
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    name: controller
spec:
  selector:
    name: controller
  clusterIP: None
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: controller
  labels:
    name: controller
spec:
  replicas: 2
  serviceName: "controller"
  template:
    metadata:
      labels:
        name: controller
    spec:
      restartPolicy: Always

      containers:
      - name: controller
        imagePullPolicy: IfNotPresent
        # Update this image to the publix OpenWhisk Image once this PR is merged.
        # https://github.com/apache/incubator-openwhisk/pull/2452
        image: projectodd/controller:openshift-latest
        command: ["/bin/bash", "-c", "/controller/bin/controller `hostname | cut -d'-' -f2`"]
        ports:
        - name: controller
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: "/ping"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
        env:
        - name: "PORT"
          value: "8080"
        - name: "COMPONENT_NAME"
          value: "controller"
        - name: "KAFKA_NUMPARTITIONS"
          value: "2"
        - name: "SERVICE_CHECK_HTTP"
          value: "/ping"
        - name: "SERVICE_CHECK_TIMEOUT"
          value: "2s"
        - name: "SERVICE_CHECK_INTERVAL"
          value: "15s"

        # Loadbalancer options
        - name: "LOADBALANCER_INVOKERBUSYTHRESHOLD"
          value: "16"

        # obsolete but "required" options
        - name: "CONSULSERVER_HOST"
          value: "consul"
        - name: "CONSUL_HOST_PORT4"
          value: "8500"

        # This needs to stay up to date with the lates runtime in Ansible Groupvars
        - name: "RUNTIMES_MANIFEST"
          value: '{ "defaultImagePrefix": "openwhisk", "defaultImageTag": "latest", "runtimes": { "nodejs": [ { "kind": "nodejs", "image": { "name": "nodejsaction" }, "deprecated": true }, { "kind": "nodejs:6", "default": true, "image": { "name": "nodejs6action" }, "deprecated": false } ], "python": [ { "kind": "python", "image": { "name": "python2action" }, "deprecated": false }, { "kind": "python:2", "default": true, "image": { "name": "python2action" }, "deprecated": false }, { "kind": "python:3", "image": { "name": "python3action" }, "deprecated": false } ], "swift": [ { "kind": "swift", "image": { "name": "swiftaction" }, "deprecated": true }, { "kind": "swift:3", "image": { "name": "swift3action" }, "deprecated": false }, { "kind": "swift:3.1.1", "default": true, "image": { "name": "action-swift-v3.1.1" }, "deprecated": false } ], "java": [ { "kind": "java", "default": true, "image": { "name": "java8action" }, "deprecated": false, "attached": { "attachmentName": "jarfile", "attachmentType": "application/java-archive" }, "sentinelledLogs": false, "requireMain": true } ] }, "blackboxes": [ { "name": "dockerskeleton" } ] }'

        # this version is the day it is deployed and should be configured every time
        - name:  "WHISK_VERSION_DATE"
          value: "2017-01-01T00:00:00Z"
        # the buildno should be the docker image tag to use
        - name: "WHISK_VERSION_BUILDNO"
          value: "latest"

        # Java options
        - name: "JAVA_OPTS"
          value: "-Xmx2g"

        # Kafka properties
        - name: "KAFKA_HOST"
          value: "kafka"
        - name: "KAFKA_HOST_PORT"
          value: "9092"

        # specific controller arguments
        - name: "CONTROLLER_OPTS"
          value: ""
        - name: "DEFAULTLIMITS_ACTIONS_INVOKES_PERMINUTE"
          value: "120"
        - name: "DEFAULTLIMITS_ACTIONS_INVOKES_CONCURRENT"
          value: "100"
        - name: "DEFAULTLIMITS_ACTIONS_INVOKES_CONCURRENTINSYSTEM"
          value: "500"
        - name: "DEFAULTLIMITS_ACTIONS_SEQUENCE_MAXLENGTH"
          value: "50"
        - name: "DEFAULTLIMITS_TRIGGERS_FIRES_PERMINUTE"
          value: "60"

        # properties for DB connection
        - name: "DB_USERNAME"
          value: "couch_user"
        - name: "DB_PASSWORD"
          value: "couch_password"
        - name: "DB_PORT"
          value: "5984"
        - name:  "DB_PROTOCOL"
          value: "http"
        - name: "DB_HOST"
          value: "couchdb"
        - name: "DB_PROVIDER"
          value: "CouchDB"
        - name: "DB_WHISK_ACTIVATIONS"
          value: "openwhisk_kube_activations"
        - name: "DB_WHISK_ACTIONS"
          value: "openwhisk_kube_whisks"
        - name: "DB_WHISK_AUTHS"
          value: "openwhisk_kube_subjects"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: invoker
data:
  init: |
    source /openwhisk_config/env
    export ORDINAL=$(hostname | cut -d'-' -f2)
    echo "Waiting for controller to be available"
    until $(curl --output /dev/null --silent --head --fail http://${CONTROLLER_HOST}:${CONTROLLER_HOST_PORT}/ping); do printf '.'; sleep 1; done
    export COMPONENT_NAME=${ORDINAL}
    /invoker/bin/invoker ${ORDINAL}
  cleanup: |
    export ORDINAL=$(hostname | cut -d'-' -f2)
    kubectl delete pod -l invoker=invoker${ORDINAL}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: invoker
  labels:
    name: invoker
spec:
  replicas: 4
  serviceName: "invoker"
  template:
    metadata:
      labels:
        name: invoker
    spec:
      restartPolicy: Always
      volumes:
      - name: openwhisk-config
        configMap:
          name: openwhisk-config
      - name: invoker-config
        configMap:
          name: invoker
      serviceAccountName: openwhisk
      containers:
      - name: invoker
        imagePullPolicy: IfNotPresent
        image: projectodd/invoker:openshift-latest
        command: [ "/bin/bash", "-o", "allexport", "/invoker_config/init" ]
        env:
          - name: "PORT"
            value: "8080"
          - name: "SERVICE_CHECK_HTTP"
            value: "/ping"
          - name: "SERVICE_CHECK_TIMEOUT"
            value: "2s"
          - name: "SERVICE_CHECK_INTERVAL"
            value: "15s"

          # Invoker instance count. Needs to match replica count
          - name: "INVOKER_INSTANCES"
            value: "1"
        ports:
        - name: invoker
          containerPort: 8080
        volumeMounts:
        - name: openwhisk-config
          mountPath: "/openwhisk_config"
        - name: invoker-config
          mountPath: "/invoker_config"
        lifecycle:
          preStop:
            exec:
              command: [ "/bin/bash", "/invoker_config/cleanup" ]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  nginx.conf: |
    events {
        worker_connections  4096;
    }

    http {
        client_max_body_size 50M;

        rewrite_log on;
        log_format combined-upstream '$remote_addr - $remote_user [$time_local] '
            '$request $status $body_bytes_sent '
            '$http_referer $http_user_agent $upstream_addr';
        access_log /logs/nginx_access.log combined-upstream;

        upstream controllers {
            # These addresses are for the controller. If there are more
            # than two invoker instances deployed then you will need to
            # add additional controller addresses.

            server controller-0.controller:8080 fail_timeout=60s;
            server controller-1.controller:8080 backup;
        }

        server {
            listen 8080 default;

            # match namespace, note while OpenWhisk allows a richer character set for a
            # namespace, not all those characters are permitted in the (sub)domain name;
            # if namespace does not match, no vanity URL rewriting takes place.
            server_name ~^(?<namespace>[0-9a-zA-Z-]+)\.localhost$;

            # proxy to the web action path
            location / {
                if ($namespace) {
                  rewrite    /(.*) /api/v1/web/${namespace}/$1 break;
                }
                proxy_pass http://controllers;
                proxy_read_timeout 70s; # 60+10 additional seconds to allow controller to terminate request
            }

            # proxy to 'public/html' web action by convention
            location = / {
                if ($namespace) {
                  rewrite    ^ /api/v1/web/${namespace}/public/index.html break;
                }
                proxy_pass http://controllers;
                proxy_read_timeout 70s; # 60+10 additional seconds to allow controller to terminate request
            }

            location /blackbox-0.1.0.tar.gz {
                root /etc/nginx;
            }

            location /OpenWhiskIOSStarterApp.zip {
                return 301 https://github.com/openwhisk/openwhisk-client-swift/releases/download/0.2.3/starterapp-0.2.3.zip;
            }

            location /cli/go/download {
                autoindex on;
                root /etc/nginx;
            }
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  type: NodePort
  selector:
    name: nginx
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 8443
      targetPort: 8443
      name: https-admin

---
apiVersion: v1
kind: Route
metadata:
  name: openwhisk
  labels:
    name: nginx
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: nginx
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
kind: Route
metadata:
  name: openwhisk-secured
  labels:
    name: nginx
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: nginx
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx
    spec:
      restartPolicy: Always
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx
      - name: logs
        emptyDir: {}
      containers:
      - name: nginx
        imagePullPolicy: IfNotPresent
        image: projectodd/whisk_nginx:openshift-latest
        ports:
        - name: http
          containerPort: 8080
        - name: https-admin
          containerPort: 8443
        volumeMounts:
        - name: nginx-conf
          mountPath: "/etc/nginx/nginx.conf"
          subPath: "nginx.conf"
        - name: logs
          mountPath: "/logs"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: install-openwhisk-catalog
  labels:
    name: install-openwhisk-catalog
spec:
  completions: 1
  serviceAccountName: openwhisk
  template:
    metadata:
      labels:
        name: install-openwhisk-catalog
    spec:
      restartPolicy: Never
      volumes:
      - name: openwhisk-config
        configMap:
          name: openwhisk-config
      serviceAccountName: openwhisk
      containers:
      - name: install-openwhisk-catalog
        image: projectodd/whisk_catalog:openshift-latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: openwhisk-config
          mountPath: "/openwhisk_config"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: preload-openwhisk-runtimes
  labels:
    name: preload-openwhisk-runtimes
spec:
  completions: 1
  serviceAccountName: openwhisk
  template:
    metadata:
      labels:
        name: preload-openwhisk-runtimes
    spec:
      restartPolicy: Never
      containers:
      - name: preload-openwhisk-nodejs6
        image: projectodd/nodejs6action:openshift-latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "echo", "success"]
      - name: preload-openwhisk-python2
        image: projectodd/python2action:openshift-latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "echo", "success"]
      - name: preload-openwhisk-python3
        image: projectodd/python3action:openshift-latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "echo", "success"]
      - name: preload-openwhisk-swift3
        image: projectodd/swift3action:openshift-latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "echo", "success"]
      - name: preload-openwhisk-java8
        image: projectodd/java8action:openshift-latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "echo", "success"]
