---
apiVersion: v1
kind: Secret
metadata:
  name: whisk.auth
type: Opaque
data:
  guest: MjNiYzQ2YjEtNzFmNi00ZWQ1LThjNTQtODE2YWE0ZjhjNTAyOjEyM3pPM3haQ0xyTU42djJCS0sxZFhZRnBYbFBrY2NPRnFtMTJDZEFzTWdSVTRWck5aOWx5R1ZDR3VNREdJd1A=
  system: Nzg5YzQ2YjEtNzFmNi00ZWQ1LThjNTQtODE2YWE0ZjhjNTAyOmFiY3pPM3haQ0xyTU42djJCS0sxZFhZRnBYbFBrY2NPRnFtMTJDZEFzTWdSVTRWck5aOWx5R1ZDR3VNREdJd1A=
---
apiVersion: v1
kind: Secret
metadata:
  name: db.auth
type: Opaque
data:
  db_password: Y291Y2hfcGFzc3dvcmQ=
  db_username: Y291Y2hfdXNlcm5hbWU=
